quarkus.langchain4j.ollama.devservices.enabled=false
quarkus.langchain4j.devservices.preload=false

quarkus.langchain4j.ollama.embedding-model.model-id=nomic-embed-text

quarkus.langchain4j.ollama.assistant.chat-model.model-id=gpt-oss:120b-cloud
quarkus.langchain4j.ollama.assistant.chat-model.temperature=0.9
quarkus.langchain4j.ollama.assistant.timeout=120s

quarkus.langchain4j.ollama.smaller.chat-model.model-id=gpt-oss:20b-cloud
quarkus.langchain4j.ollama.smaller.chat-model.temperature=0
quarkus.langchain4j.ollama.smaller.timeout=60s
quarkus.langchain4j.ollama.smaller.chat-model.num-predict=512

quarkus.langchain4j.ollama.log-requests=true


