quarkus.http.port=8080

quarkus.langchain4j.ollama.chat-model.model-id=deepseek-v4-pro:cloud
quarkus.langchain4j.ollama.chat-model.temperature=0.4
quarkus.langchain4j.timeout=120s

quarkus.langchain4j.ollama.smaller.chat-model.model-id=gpt-oss:20b-cloud
quarkus.langchain4j.ollama.smaller.chat-model.temperature=0.5
quarkus.langchain4j.ollama.smaller.timeout=60s

quarkus.langchain4j.devservices.preload=false
quarkus.langchain4j.ollama.devservices.enabled=false

quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true

quarkus.rest-client.vendedor.url=http://localhost:8081

negociacao.max-rodadas=5
