quarkus.http.port=8081

quarkus.langchain4j.ollama.chat-model.model-id=deepseek-v4-pro:cloud
quarkus.langchain4j.ollama.chat-model.temperature=0.4
quarkus.langchain4j.timeout=120s

quarkus.langchain4j.devservices.preload=false
quarkus.langchain4j.ollama.devservices.enabled=false

quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true
