quarkus.langchain4j.ollama.chat-model.model-id=deepseek-v4-pro:cloud
quarkus.langchain4j.ollama.chat-model.temperature=0
quarkus.langchain4j.ollama.chat-model.format=json
quarkus.langchain4j.timeout=240s

quarkus.langchain4j.ollama.smaller.chat-model.model-id=gpt-oss:20b-cloud
quarkus.langchain4j.ollama.smaller.chat-model.temperature=0
quarkus.langchain4j.ollama.smaller.timeout=120s
quarkus.langchain4j.ollama.smaller.chat-model.num-predict=2048

quarkus.langchain4j.devservices.preload=false
quarkus.langchain4j.ollama.devservices.enabled=false

quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true
