quarkus.langchain4j.ollama.chat-model.model-id=gpt-oss:120b-cloud
quarkus.langchain4j.ollama.chat-model.temperature=0.7
quarkus.langchain4j.timeout=120s

quarkus.langchain4j.ollama.smaller.chat-model.model-id=gpt-oss:20b-cloud
quarkus.langchain4j.ollama.smaller.chat-model.temperature=0
quarkus.langchain4j.ollama.smaller.timeout=60s
quarkus.langchain4j.ollama.smaller.chat-model.num-predict=512

quarkus.langchain4j.devservices.preload=false
quarkus.langchain4j.ollama.devservices.enabled=false

quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true
