quarkus.langchain4j.ollama.chat-model.model-id=gpt-oss:120b-cloud
quarkus.langchain4j.ollama.chat-model.temperature=0.4
quarkus.langchain4j.timeout=180s

quarkus.langchain4j.devservices.preload=false
quarkus.langchain4j.ollama.devservices.enabled=false

quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true

quarkus.thread-pool.max-threads=16
